twig:
    default_path: '%kernel.project_dir%/templates'
    
    form_themes: ['@TetranzSelect2Entity/Form/fields.html.twig']

    globals:
        search_service: '@App\Service\SearchService'
        parameter_service: '@App\Service\ParameterService'
